name: learn-github-actions
run-name: ${{github.actor}} is learning Github Actions
on: [push]
jobs: 
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - uses: actions/setup-node@3
        with:
          node-version: '18'
      - run: npm install -g bats
      - run: bats -v